### ISSUE TITLE
感谢wklken

### ISSUE THREAD

**Issue by giantray** [wklken/stackoverflow-py-top-qa#12]
wklken，受到你的启发，也参考了你的排版，我也搞了个stackoverflow翻译精选，不过我这个是java版本的。
https://github.com/giantray/stackoverflow-java-top-qa
已在文档contribution中署上你的名字，谢谢

**Comment by wklken** [comment]
hi giantray:
    非常感谢，这个翻译持续了很长一段时间，中间断了几次，最终在另一个同学帮助下完成了刚开始定的目标。


    兴趣加坚持，在某段时期内，会对成长有很大帮助。


    祝好：)


Sent from Mail Master
On 08/18/2015 17:59, giantray wrote:

wklken，受到你的启发，也参考了你的排版，我也搞了个stackoverflow翻译精选，不过我这个是java版本的。
https://github.com/giantray/stackoverflow-java-top-qa
已在文档contribution中署上你的名字，谢谢
