### ISSUE TITLE
When I tried to translate another five or more QA, I found that I'm not in contributors.

### ISSUE THREAD

**Issue by shnode** [wklken/stackoverflow-py-top-qa#9]
What should I do?

**Comment by wklken** [comment]
sorry, 目测是pr合并的方式有问题导致的，上次手动解的冲突，不知道中间哪步出了问题。非常抱歉，一会回去我看下怎么搞

Sent from Mail Master
On 01/05/2015 21:05, Sinux wrote:

What should I do?

**Comment by wklken** [comment]
晕死, 没找到原因, 明明是在commit里面可以看到你的提交记录, 但是无法找到没有出现在贡献者列表的原因.

怀疑我在合并冲突的时候出的问题(是按照github提示的合并命令行合并的啊, 囧)

-------------------

暂时在README.md里面加入了, sorry

-------------------

是否可以测试下? 你拉取最新的分支, 加几行文字, 提交PR给我, 我测试下合并pr后的结果

**Comment by shnode** [comment]
https://github.com/wklken/stackoverflow-py-top-qa/graphs/contributors
已经可以看到我的贡献了。
今晚会根据剩下的顺序翻译一部分，我们别翻译冲突了。
